spring:
  datasource:
    url: jdbc:mysql://139.199.152.218:3306/webdata?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#       defaultZone: http://39.107.107.22:6767/eureka/,http://39.107.107.22:6768/eureka/
# instance: 
#   prefer-ip-address: true
##   ip-address: 39.107.107.22
#   instance-id: graduate:8989


logging:
  config: classpath:log4j2.xml
server:
  port: 8989
mybatis:
  typeAliasesPackage: com.graduate.Entity
  mapper-locations: classpath:mapper/*Mapper.xml